spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 03b0b14d4fbf423e03b10178a227d48c
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajunsu5@gmail.com
    password: knjsqpcpktqcktpo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true